### PR TITLE
Travis build:  openjdk8, openjdk11

### PR DESCRIPTION
**Pull request by sullis**

### CODE REVIEW

**Comment by mikesamuel** [comment]
Why?

**Comment by sullis** [comment]
April 15, 2019:   **Ubuntu Xenial 16.04 as the default Travis CI build environment**

link: https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment

link: https://docs.travis-ci.com/user/reference/xenial/#differences-from-the-trusty-images

`Pre-installed JVMs: openjdk8, openjdk10, and openjdk11`

**Comment by sullis** [comment]
for reference:  

-> Apache Zookeeper uses Travis-CI
-> Apache Zookeeper replaced OracleJDK with openjdk

link: https://github.com/apache/zookeeper/pull/1005

link: https://github.com/apache/zookeeper/commit/5e7d88bc27c3d1d7aa0ebb77e0609ae0a39cf309

**Comment by sullis** [comment]
Similar change in the [kotlinpoet] project:

https://github.com/square/kotlinpoet/commit/6d6eed8e635d467b0ee6560e96a003f80f3b7224

**Comment by mikesamuel** [comment]
Thanks for explaining.

**Comment by mikesamuel** [comment]
Thanks for the patch.

I pulled this locally, and switch to dist:trusty which https://docs.travis-ci.com/user/reference/trusty/#jvm-clojure-groovy-java-scala-images indicates has the widest range of available JVM versions.

I committed a version of your PR with my local edits.

**Pull request closed without merging**
