### PR TITLE
Fix repeatedly adding rel values

### LINKED ISSUE #145: Html sanitizer adds rel="nofollow" even if it pre-exists
Hi,

Consider the input as 
String input = ```html <a href='www.google.com' rel='nofollow'></a>```;

In my policy factory i have requireRelNofollowOnLinks() ON.

Expected output : ```html <a href='www.google.com' rel='nofollow'></a> ```;

Actual output : ```html <a href="www.google.com" rel="nofollow" rel="nofollow"></a>```

Sometimes it adds multiple rel="nofllow" which will result in more than 2 rel="follow" in single tag.

Thanks

### LINKED ISSUE #306: Html sanitizer repeatedly adds rel="noopener noreferrer" even if it's pre-exist
Thanks for reporting an issue.

Please report **security vulnerabilities** via
[OWASP's vulnerability rewards program](https://bugcrowd.com/owaspjavasanitizer).

Please report all other feature requests and issues here.

_**### So we are using OWASP/java-html-sanitizer to sanitize the html. It adds noopener noreferrer everytime we sanitize it. It should not add noopener noreferrer if it's already exists in the HTML.**_

**Also note that we have already upgraded the jar to latest one i.e owasp-java-html-sanitizer-20220608.1.jar**

For bugs, please include
**Input**
````
```
<p dir="ltr"><a href="http://bbbbb" rel="noopener noreferrer" target="_blank">www.bbbbbbb.com</a></p>
```
````
**Output I am getting right now**
````
```
<p dir="ltr"><a href="http://bbbbb" rel="noopener noreferrer noopener noreferrer" target="_blank">www.bbbbbbb.com</a></p>
```
````

**Expected output**
````
```
<p dir="ltr"><a href="http://bbbbb" rel="noopener noreferrer" target="_blank">www.bbbbbbb.com</a></p>
```
````

**### Note**
I found similar issue https://github.com/OWASP/java-html-sanitizer/issues/145 here which is very old issue but it's not resolved yet. Hence creating new one. Please help me on resolving it. It's urgent

If you're having trouble putting HTML in markdown, try using
an HTML [code block](https://help.github.com/articles/creating-and-highlighting-code-blocks/):

### PR DESCRIPTION
**Pull request by csware**
Fixes #145 
Fixes #306

### CODE REVIEW

**Comment by csware** [comment]
Parts of this PR are already in commit e8aa0f1b75ab81eea97ef173fefc023a3e16963d

**Comment by mikesamuel** [comment]
> Parts of this PR are already in commit [e8aa0f1](https://github.com/OWASP/java-html-sanitizer/commit/e8aa0f1b75ab81eea97ef173fefc023a3e16963d), but there are more cases to consider...

Ok.  I see the changes to case folding.

**Comment by csware** [comment]
It's not really the case folding, its more about having already duplicate rels in the input.

**Comment by yadue** [comment]
@mikesamuel when it will be released?

**Comment by jmanico** [comment]
Noted Daniel and others

**Pull request merged**
